name: scraping
on:
  workflow_dispatch:

jobs:
  get-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          
      - name: Install module
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install --with-deps firefox
                  
      - name: Run scraper
        run: python main.py
